### ISSUE TITLE
Add multiple tags

### ISSUE THREAD

**Issue by jossefaz** [fez-github/obsidian-multi-properties#10]
At present, users have the option to add tags by typing 'tags' in the field name. However, it is common to use multiple tags simultaneously. Is it possible to incorporate the functionality to add multiple tags? I attempted to add another 'tags' property, but encountered a 'duplicate' error.
<img width="544" alt="Screenshot 2023-12-25 at 21 06 16" src="https://github.com/fez-github/obsidian-multi-properties/assets/61141682/2b1a00cd-31fb-4375-a1b7-89c8b731ba8a">

**Comment by jossefaz** [comment]
I actually discovered that we can add multiple tags by repeating the action and uncheck the override property...
Still would be a great option to be able to add multiple tags at once

**Comment by fez-github** [comment]
It's already possible to add multiple tags at once.  Use a single "tags" entry field, and enter all the tags you wish to add, separated by commas.(ex. tag1,tag2,tag3)

This is mentioned in the text in the form.  "If you want to make a List property, use the Text data type and separate each value with commas."
