### ISSUE TITLE
no #results in search bar

### ISSUE THREAD

**Issue by notuntoward** [fez-github/obsidian-multi-properties#19]
From the README, I understand that I should be able to add and remove properties in a search result by clicking `#results`.  But I don't see `#results` (screenshot), and if I right click on a file in the search results, I don't see a way to edit properties.  Am I missing something?

![image](https://github.com/fez-github/obsidian-multi-properties/assets/3851891/ec062fa7-6e62-430c-ac2a-27a20a6ea543)

**Comment by fez-github** [comment]
Probably should've formatted it better, but #results isn't a specific tag.  I meant the number of results section that appears in a search.  Where your screenshot says "2 results"?  Click that, and add/remove properties will show up.  The # was meant to indicate whatever number would show up there.

**Comment by notuntoward** [comment]
Ah, of course.  I was looking for a literal tag.  It works.  Thanks.
