### ISSUE TITLE
Edit or remove properties

### ISSUE THREAD

**Issue by imeed166** [fez-github/obsidian-multi-properties#2]
I don't know if it's in the scope of the plugin, but the ability to remove or edit properties of multiples files would be very useful.

**Comment by fez-github** [comment]
Editing properties is technically already possible by typing in the name of the property you want to change and the value you want to replace it with.  However, the type must be the same.(can't overwrite dates with text)  I did have the thought of appending new values to existing properties and turn them into lists, but I never implemented it.  I'll try looking into it.  It should work with turning text into a list(that's how I do tags already) but IDK if it'll work with other types, like turning a date into a list of dates.

As for removing properties, now that I think about it, it's probably not that complicated.  I could probably loop through a selection and process each frontmatter name, and create a form of those names for the user to pick and remove certain properties.

I'll look more into both of these.  Not sure when I'll get around to implementing them, but I probably should have them, considering that mass-adding properties can be a dangerous action and it'd be best to have tools to correct any issues.
