### ISSUE TITLE
Feature Request: Android Support

### ISSUE THREAD

**Issue by mardybardy** [fez-github/obsidian-multi-properties#20]
Just curious as to why this doesn't support Android as the code is all JS/TS. I'm on a Samsung Galaxy Fold 5 and would love to use it but can't install because of the "This plugin does not support your device." message.

**Comment by fez-github** [comment]
Should work on mobile in version 1.1.1.

**Comment by mardybardy** [comment]
Awesome, just installed it. I found a way around it using the linter plugin in the end but good to have it for the future, thanks!
