### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by imeed166** [fez-github/obsidian-multi-properties#9]
This is just a suggestion, but you could add 2 things to your readme :
- the fact that you can update existing properties with the "add property" menu
- the fact that you can edit properties from the search menu, which is in my opinion more useful and more powerful than folder or file selection.

**Comment by fez-github** [comment]
I agree.  I haven't used the Search functionality myself yet, so I didn't think about how powerful it really is.  

There were some other things I wanted to change, so I went and updated the README now.
